---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorapiuser
  labels:
    app: blazorapiuser
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: blazorapiuser
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blazorapiuser
    spec:
      containers:
      - name: blazorapiuser
        image: nguyenvantu/blazorapiuser:v4
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: blazorapiuser-env
      terminationGracePeriodSeconds: 180