---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooksapi
  labels:
    app: webhooksapi
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: webhooksapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webhooksapi
    spec:
      containers:
      - name: webhooksapi
        image: nguyenvantu/webhooksapi:aa55f181b5da
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: webhooksapi-env
      terminationGracePeriodSeconds: 180