---
apiVersion: v1
kind: Service
metadata:
  name: webhooksapi
  namespace: multiapp

spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: webhooksapi
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443