---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorfiles
  labels:
    app: blazorfiles
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: blazorfiles
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blazorfiles
    spec:
      containers:
      - name: blazorfiles
        image: nguyenvantu/blazorfiles:2a7e8c115b31f741fb69f1005e9c17bb49a858e801c7ee4eaa952cdc42e46ea7
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: blazorfiles-env
      terminationGracePeriodSeconds: 180