---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazoridentityapi
  labels:
    app: blazoridentityapi
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: blazoridentityapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blazoridentityapi
    spec:
      containers:
      - name: blazoridentityapi
        image: nguyenvantu/blazoridentityapi:679b492bbcbaec0c1af1ad8011bb777acc7265421594e7b69f8e57c2afd519f9
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: blazoridentityapi-env
      terminationGracePeriodSeconds: 180