---
apiVersion: v1
kind: Service
metadata:
  name: blazoridentityapi
spec:
  type: LoadBalancer
  selector:
    app: blazoridentityapi
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
