---
apiVersion: v1
kind: Service
metadata:
  name: blazoridentityapi
spec:
  type: ClusterIP
  selector:
    app: blazoridentityapi
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
