---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooksclient
  labels:
    app: webhooksclient
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: webhooksclient
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webhooksclient
    spec:
      containers:
      - name: webhooksclient
        image: nguyenvantu/webhooksclient:b2e630e15ca32bab4755d3e19a1638c7b5e7f42d035678913c262fa52bc417b7
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: webhooksclient-env
      terminationGracePeriodSeconds: 180