---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooksclient
  labels:
    app: webhooksclient
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: webhooksclient
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webhooksclient
    spec:
      containers:
      - name: webhooksclient
        image: nguyenvantu/webhooksclient:4869d6ab6c1282edc9b0b8d0805549df3c0b65241543b90e1b0b9bd25dfa6016
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: webhooksclient-env
      terminationGracePeriodSeconds: 180