---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooksclient
  labels:
    app: webhooksclient
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: webhooksclient
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webhooksclient
    spec:
      containers:
      - name: webhooksclient
        image: nguyenvantu/webhooksclient:0d8e5e0bfd13f264c545de877fa1e6c9862c5e630fea8e3afcb7914597d97685
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: webhooksclient-env
      terminationGracePeriodSeconds: 180