---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooksclient
  labels:
    app: webhooksclient
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: webhooksclient
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webhooksclient
    spec:
      containers:
      - name: webhooksclient
        image: nguyenvantu/webhooksclient:08b974076e6a3cee19445be303a97881f6d70e7be42492905e053444f6edb95c
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: webhooksclient-env
      terminationGracePeriodSeconds: 180